# Generated by Django 5.1.6 on 2025-02-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud_model',
            name='phone',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
